- name: pickup-points-modal
  referenceId: V5G7Q14G
  description: SonarQube scan for pickup-points-modal
  build:
    provider: dkcicd
    pipelines:
      - name: node-ci-v2
        parameters:
          sonarProjectName: pickup-points-modal
          nodeVersion: 20-bookworm
          nodeCommands:
            - run test:coverage
        runtime:
          architecture: amd64
        when:
          - event: pull_request
            source: branch
          - event: push
            source: branch
            regex: main
